name: lithox_epoxy_app
description: A Flutter app for Lithox epoxy flooring service booking
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # UI & Navigation
  go_router: ^12.0.0

  # Image Handling
  image_picker: ^1.0.4

  # Email functionality
  url_launcher: ^6.3.0
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

  # UI Components
  cupertino_icons: ^1.0.2
  
  # Video Player
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
